version: '3'
services:
  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:mysecretpassword@db:5432/postgres
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
      # PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_OPENAPI_SERVER_PROXY_URI: http://172.105.26.204:3000/
    depends_on:
      - db
  db:
    image: postgres:13.4
    container_name: db
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
      - ./code-sample/postgrest.sql:/docker-entrypoint-initdb.d/init.sql
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - "8080:8080"
    environment:
      API_URL: http://172.105.26.204:3000/
    depends_on:
      - postgrest
